---
title: "622 HW2 GROUP"
author: "Jessica Valencia"
date: "2023-03-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_package}
#install.packages("RedditExtractoR")
#devtools::install_github('ivan-rivera/RedditExtractor')
library(RedditExtractoR)
```

#SCRAPING POSTS##################################
```{r find_thread_url_msu}
#msu_urls = find_thread_urls(keywords='MSU Shooting', period='month')
#dim(msu_urls)
#head(msu_urls)
```

```{r get_thread_content}
#msu_content = get_thread_content(msu_urls$url[1:25])

#names(msu_content)

#dim(msu_content$threads)
#head(msu_content$threads)
```
```{r}
#dim(msu_content$comments)
#head(msu_content$comments)
```

```{r}
#write.csv(msu_urls, "C:\\Users\\valen\\Downloads\\msudata.csv", row.names=FALSE)
```


```{r}
#where you will bring in the data
library(readr)
msu_data <- read_csv("C:/Users/valen/Downloads/msudata.csv")
View(msu_data)
```

#MERGING ALL DATA FILES###################
```{r}
library(readr)
#msudata1 <- read_csv("C:/Users/valen/Downloads/msudata (1).csv")
#View(msudata_1_)
```

```{r}
#msudata2 <- read_csv("C:/Users/valen/Downloads/msudata2.csv")
#View(msudata2)
```

```{r}
#msudata3 <- read_csv("C:/Users/valen/Downloads/msudata3.csv")
#View(msudata3)
```

```{r}
#msudata4 <- read_csv("C:/Users/valen/Downloads/msudata4.csv")
#View(msudata4)
```

```{r}
#msudata5 <- read_csv("C:/Users/valen/Downloads/msudata5.csv")
#View(msudata5)
```

```{r}
#msudata6 <- read_csv("C:/Users/valen/Downloads/msudata6.csv")
#View(msudata6)
```

#CREATING CSV FOR MERGED DATA################# 
```{r}
#full_data<- rbind(msudata1,msudata2,msudata3,msudata4,msudata5,msudata6)
#View(full_data)
#write.csv(full_data, "C:\\Users\\valen\\Downloads\\msufulldata.csv", #row.names=FALSE)
```

#ACCESS THE FULL DATA 
```{r}
#where you will bring in the data
msufulldata <- read_csv("C:/Users/valen/Downloads/msufulldata.csv")
View(msufulldata)
```
